### Tạo dữ liệu
Tạo bộ trainset là mảng 2 chiều có 10.000 phần tử, mỗi phần tử là mảng 1 chiều chứa 1 số thực trong khoảng [0:1]

In [1]:
import numpy as np

data = np.random.random(10000)
data.shape = 10000, 1
print(data[:5])  # Look at the first five observations

[[0.55703131]
 [0.41662379]
 [0.92448384]
 [0.81816831]
 [0.14259306]]


### Tạo label

In [2]:
labels = np.array(data >= .5, dtype=int)
print(labels[:5])  # Look at the first five labels

[[1]
 [0]
 [1]
 [1]
 [0]]


### Build neural network architect

In [65]:
from keras import Sequential
from keras.layers import Dense

model = Sequential([
    Dense(units=16, input_shape=(1,), activation='relu'),
    Dense(units=2, activation='softmax'),
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 16)                32        
_________________________________________________________________
dense_17 (Dense)             (None, 2)                 34        
Total params: 66
Trainable params: 66
Non-trainable params: 0
_________________________________________________________________


### Training

In [66]:
model.fit(x=data, y=labels, epochs=10, verbose=1, validation_split=.1)

Epoch 1/10
282/282 [==============================] - 1s 4ms/step - loss: 0.6074 - accuracy: 0.6648 - val_loss: 0.4965 - val_accuracy: 0.8370
Epoch 2/10
282/282 [==============================] - 1s 4ms/step - loss: 0.4119 - accuracy: 0.8920 - val_loss: 0.3293 - val_accuracy: 0.9370
Epoch 3/10
282/282 [==============================] - 1s 4ms/step - loss: 0.2743 - accuracy: 0.9608 - val_loss: 0.2201 - val_accuracy: 0.9990
Epoch 4/10
282/282 [==============================] - 1s 4ms/step - loss: 0.1871 - accuracy: 0.9873 - val_loss: 0.1526 - val_accuracy: 0.9940
Epoch 5/10
282/282 [==============================] - 1s 4ms/step - loss: 0.1370 - accuracy: 0.9930 - val_loss: 0.1162 - val_accuracy: 0.9930
Epoch 6/10
282/282 [==============================] - 1s 4ms/step - loss: 0.1092 - accuracy: 0.9960 - val_loss: 0.0949 - val_accuracy: 0.9940
Epoch 7/10
282/282 [==============================] - 1s 4ms/step - loss: 0.0921 - accuracy: 0.9951 - val_loss: 0.0821 - val_accuracy: 0.9910
Epoch 

### Predict

In [71]:
test_set = [ 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
predictions = model.predict(np.array(test_set))
print(predictions)

predicted = np.argmax(predictions, axis=1)
print(predicted)


[[9.9675399e-01 3.2459756e-03]
 [9.9645364e-01 3.5463821e-03]
 [9.9612552e-01 3.8744819e-03]
 [9.9502397e-01 4.9761017e-03]
 [9.3343055e-01 6.6569440e-02]
 [4.9268994e-01 5.0731003e-01]
 [6.3026063e-02 9.3697399e-01]
 [4.6373233e-03 9.9536264e-01]
 [3.2258101e-04 9.9967742e-01]
 [2.2349210e-05 9.9997771e-01]]
[0 0 0 0 0 1 1 1 1 1]


### Save model

In [68]:
model.save('simple_model.keras')

### Load model

In [3]:
import keras
import numpy as np

model = keras.models.load_model('simple_model.keras')

test_set = [0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0]
predictions = model.predict(np.array(test_set))

predicted = np.argmax(predictions, axis=1)
print(predicted)

[[2.2349210e-05 9.9997771e-01]
 [3.2258101e-04 9.9967742e-01]
 [4.6373233e-03 9.9536264e-01]
 [6.3026063e-02 9.3697399e-01]
 [4.9268994e-01 5.0731003e-01]
 [9.3343055e-01 6.6569440e-02]
 [9.9502397e-01 4.9761017e-03]
 [9.9612552e-01 3.8744819e-03]
 [9.9645364e-01 3.5463821e-03]
 [9.9675399e-01 3.2459756e-03]]
[1 1 1 1 1 0 0 0 0 0]
